
import './globals.css'
import '../styles/global.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { LoginProvider } from '@/Context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }){
  return (
    <LoginProvider>
      <html lang="en">
        <body className={inter.className}>
          {children}
        </body>
      </html>
    </LoginProvider>
  )
}
