
import './globals.css'
import '../styles/global.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { UserProvider, AdminProvider } from '@/Context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }){
  return (
    <UserProvider>
      <AdminProvider>
        <html lang="en">
          <body className={inter.className}>
            {children}
          </body>
        </html>
      </AdminProvider>
    </UserProvider>
  )
}
